name: CI/CD workflow for Maven Build
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean install
        working-directory: CumbresMalvinas
        env:
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}

      - name: Run tests with Maven (and show output)
        run: mvn test -X
        working-directory: CumbresMalvinas
